# Generated by Django 4.2 on 2023-05-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_unvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unvote',
        ),
    ]
